debug

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -16,49 +16,34 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Pull latest Playwright Docker image
-        run: docker pull andreybitkov/playwright-tests:latest
+      - name: Install Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: 'npm'
 
-      # Отладка: Проверяем файлы перед запуском тестов
-      - name: Debug Files in CI/CD
-        run: ls -la ${{ github.workspace }}
+      - name: Install Dependencies
+        run: npm install --legacy-peer-deps
 
-      # Запуск Smoke Tests через `npm run test:smoke`
+      - name: Install Playwright Browsers
+        run: npx playwright install --with-deps
+
       - name: Run Smoke Tests
         if: github.event_name == 'push'
-        run: |
-          docker run --rm \
-            --platform linux/amd64 \
-            -v ${{ github.workspace }}:/app \
-            -w /app andreybitkov/playwright-tests:latest \
-            sh -c "npm run test:smoke"
+        run: npm run test:smoke -- --reporter=allure-playwright
 
-      # Запуск Regression Tests через `npm run test:all`
       - name: Run Regression Tests
         if: github.event_name == 'pull_request'
-        run: |
-          docker run --rm \
-            --platform linux/amd64 \
-            -v ${{ github.workspace }}:/app \
-            -w /app andreybitkov/playwright-tests:latest \
-            sh -c "npm run test:all"
+        run: npm run test:all -- --reporter=allure-playwright
 
-      # Запуск API Tests через `npm run test:api`
       - name: Run API Tests
-        run: |
-          docker run --rm \
-            --platform linux/amd64 \
-            -v ${{ github.workspace }}:/app \
-            -w /app andreybitkov/playwright-tests:latest \
-            sh -c "npm run test:api"
+        run: npm run test:api -- --reporter=allure-playwright
 
-      # Отладка: Проверяем, есть ли HTML-репорт перед загрузкой
-      - name: Debug Playwright Report Files
-        run: ls -la ${{ github.workspace }}/playwright-report || echo "No report found!"
+      - name: Generate Allure Report
+        run: npx allure-playwright generate allure-results -o allure-report || echo "Allure report generation failed!"
 
-      # Загружаем HTML-отчет Playwright в артефакты CI/CD
-      - name: Upload Playwright Report as an Artifact
+      - name: Upload Allure Report as an Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: playwright-report
-          path: playwright-report/**
+          name: allure-report
+          path: allure-report/**
