debug

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -19,28 +19,44 @@ jobs:
       - name: Pull latest Playwright Docker image
         run: docker pull andreybitkov/playwright-tests:latest
 
-      - name: Run Smoke Tests
-        if: github.event_name == 'push'
+      - name: Debug Files in CI/CD
+        run: ls -la ${{ github.workspace }}
+
+      - name: Debug Files Inside Docker
         run: |
           docker run --rm \
             -v ${{ github.workspace }}:/app \
             -w /app andreybitkov/playwright-tests:latest \
-            sh -c "npx playwright test --grep @smoke --reporter=html"
+            sh -c "ls -la /app && ls -la /app/node_modules/.bin/ && npx playwright --version || echo 'Playwright is missing!'"
+
+      - name: Run Smoke Tests
+        if: github.event_name == 'push'
+        run: |
+          docker run --rm \
+            --platform linux/amd64 \
+            -v ${{ github.workspace }}:/app \
+            -w /app andreybitkov/playwright-tests:latest \
+            sh -c "/app/node_modules/.bin/playwright test --grep @smoke --reporter=html"
 
       - name: Run Regression Tests
         if: github.event_name == 'pull_request'
         run: |
           docker run --rm \
+            --platform linux/amd64 \
             -v ${{ github.workspace }}:/app \
             -w /app andreybitkov/playwright-tests:latest \
-            sh -c "npx playwright test --grep @regression --reporter=html"
+            sh -c "/app/node_modules/.bin/playwright test --grep @regression --reporter=html"
 
       - name: Run API Tests
         run: |
           docker run --rm \
+            --platform linux/amd64 \
             -v ${{ github.workspace }}:/app \
             -w /app andreybitkov/playwright-tests:latest \
-            sh -c "npx playwright test --grep @api --reporter=html"
+            sh -c "/app/node_modules/.bin/playwright test --grep @api --reporter=html"
+
+      - name: Debug Playwright Report Files
+        run: ls -la ${{ github.workspace }}/playwright-report || echo "No report found!"
 
       - name: Upload Playwright Report as an Artifact
         uses: actions/upload-artifact@v4
